/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryId = IDL.Nat;
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'machineInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const InquiryInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'machineInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func([InquiryInput], [Inquiry], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryId = IDL.Nat;
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'machineInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const InquiryInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'machineInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func([InquiryInput], [Inquiry], []),
  });
};

export const init = ({ IDL }) => { return []; };